project:
  type: website
  output-dir: docs

website:
  title: "Cloud tools for scientific analyses at DESI"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/mariariveraaraya/cloud
        text: GitHub
    style: docked
    contents:
      - section: "Welcome!"
        contents: 
          - index.qmd
  #      text: Home
      - section: "Tutorials"
        contents: 
          - cloud_concepts/python_query_synapse_views.ipynb
          - cloud_concepts/QLD Protected areas and wildlife spatial joins and counts.ipynb
  #    - href: schedule.qmd
  #      text: Schedule
  #    - href: materials.qmd
  #     text: Materials
   #   - href: https://github.com/mariariveraaraya/cloud/discussions
    #    text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

