---
title: "Cloud tools for scientific analyses in the QESD cloud platform"
---

! Important: This page is in construction. We will be adding additional tutorials to this public version soon.

The Queensland Environmental Science Data (QESD) Platform is a collection of modern, secure, and interoperable cloud components. These components, which include infrastructure, applications, and tools, are scalable and available on-demand on a pay-as-you-go basis for data processing.

These tutorials are a combination of narrative, links, code, and outputs. They have been developed for live demos during the implementation of the Queensland Environmental Science Data (QESD) cloud Platform at the Department of Environment, Science and Innovation, and are available for self-paced learning.

## Introduction to cloud-based scientific analysis tools

Increasing data volumes and technological advancements are ushering us into a new era of scientific analysis. One such advancement is cloud computing, enabling users to effectively process and analyse vast amounts of data from anywhere in the world. These tutorials will introduce you to cloud-based tools employed in scientific analysis in the QESD platform. Check out [our module](https://mariariveraaraya.github.io/cloud_training/) that covers cloud fundamental concepts.

## [Access to data in the QESD Cloud Platform](cloud_concepts/python_query_synapse_views.ipynb)

This section includes detailed processes on how to login from your local integrated development environment to read data from Synapse.

## [Geospatial case study and best practice examples](cloud_concepts/QLD Protected areas and wildlife spatial joins and counts.ipynb)

This section features a workflow that demonstrate how we can use cloud tools available in the QESD cloud platform to perform geopatial analyses.

## Coming up:

- Integrating Cloud Tools in your research
- Case Studies and Best Practice Examples
- Resources and continuous learning
